const PRODUCTS = [
  { id: 1, name: "Nike Air Force 1 Mid Black Red", brand: "Nike", category: "lifestyle", image: "images/01.jpg", featured: true },
  { id: 2, name: "On Cloudmonster White Sand", brand: "On Running", category: "running", image: "images/02.jpg", featured: false },
  { id: 3, name: "On Cloudmonster All White", brand: "On Running", category: "running", image: "images/03.jpg", featured: false },
  { id: 4, name: "On Cloudmonster Black White", brand: "On Running", category: "running", image: "images/04.jpg", featured: true },
  { id: 5, name: "On Cloudmonster Flame Orange", brand: "On Running", category: "running", image: "images/05.jpg", featured: false },
  { id: 6, name: "On Cloudmonster Ice Turquoise", brand: "On Running", category: "running", image: "images/06.jpg", featured: false },
  { id: 7, name: "Veja Campo Black White", brand: "Veja", category: "lifestyle", image: "images/07.jpg", featured: false },
  { id: 8, name: "Veja Campo White Black", brand: "Veja", category: "lifestyle", image: "images/08.jpg", featured: false },
  { id: 9, name: "Nike Air Force 1 Low NOCTA White", brand: "Nike", category: "lifestyle", image: "images/09.jpg", featured: false },
  { id: 10, name: "Nike Lunar Force 1 Duckboot Black", brand: "Nike", category: "boot", image: "images/10.jpg", featured: false },
  { id: 11, name: "Nike Lunar Force 1 Duckboot '17 Black", brand: "Nike", category: "boot", image: "images/11.jpg", featured: false },
  { id: 12, name: "On Cloudrock Waterproof Olive Black", brand: "On Running", category: "boot", image: "images/12.jpg", featured: false },
  { id: 13, name: "On Cloud X 3 White Black", brand: "On Running", category: "running", image: "images/13.jpg", featured: false },
  { id: 14, name: "On Cloud X Black", brand: "On Running", category: "running", image: "images/14.jpg", featured: false },
  { id: 15, name: "Nike Air Max 720 Triple Black", brand: "Nike", category: "lifestyle", image: "images/15.jpg", featured: true },
  { id: 16, name: "Nike Air Max 720 Triple White", brand: "Nike", category: "lifestyle", image: "images/16.jpg", featured: false },
  { id: 17, name: "Nike Air Max 720 White", brand: "Nike", category: "lifestyle", image: "images/17.jpg", featured: false },
  { id: 18, name: "New Balance 9060 Black Silver", brand: "New Balance", category: "lifestyle", image: "images/18.jpg", featured: false },
  { id: 19, name: "Air Jordan 12 Retro Royalty Taxi", brand: "Jordan", category: "basketball", image: "images/19.jpg", featured: true },
  { id: 20, name: "Air Jordan 12 Retro Red Taxi", brand: "Jordan", category: "basketball", image: "images/20.jpg", featured: false },
  { id: 21, name: "Air Jordan 11 Retro DMP Gratitude", brand: "Jordan", category: "basketball", image: "images/21.jpg", featured: false },
  { id: 22, name: "Air Jordan 11 Retro Cool Grey", brand: "Jordan", category: "basketball", image: "images/22.jpg", featured: false },
  { id: 23, name: "Air Jordan 1 Low Paris White Grey", brand: "Jordan", category: "lifestyle", image: "images/23.jpg", featured: false },
  { id: 24, name: "Nike Air Max Intrlk Black White", brand: "Nike", category: "lifestyle", image: "images/24.jpg", featured: false },
  { id: 25, name: "Air Jordan 1 Retro High OG Chicago", brand: "Jordan", category: "lifestyle", image: "images/25.jpg", featured: true },
  { id: 26, name: "On Cloudrock 2 Waterproof Grey", brand: "On Running", category: "boot", image: "images/26.jpg", featured: false },
  { id: 27, name: "On Cloudrock 2 Waterproof Sage Green", brand: "On Running", category: "boot", image: "images/27.jpg", featured: false },
  { id: 28, name: "On Cloudrock 2 Waterproof Rose", brand: "On Running", category: "boot", image: "images/28.jpg", featured: false },
  { id: 29, name: "Nike Air Max 720 Black", brand: "Nike", category: "lifestyle", image: "images/29.jpg", featured: false },
  { id: 30, name: "Nike Air Max 720 Black White", brand: "Nike", category: "lifestyle", image: "images/30.jpg", featured: false },
  { id: 31, name: "On Cloudrock 2 Waterproof All Black", brand: "On Running", category: "boot", image: "images/31.jpg", featured: false }
];
